version: "3.3"

services:

  mariadb:
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
    volumes:
      - /home/kaktyc/IdeaProjects/BusTickets/DB:/var/lib/mysql
    networks:
      - db

networks:
  db:
    driver: bridge